### ISSUE TITLE
Logistic Vessel gets stuck at next to logistic stations

### ISSUE THREAD

**Issue by Chrysaour** [Touhma/DSP_Plugins#39] opened 2021-02-28 18:41 UTC
**Issue**:
When using intesteller logistic vessel to retrieve stuff from Gas Giant, it appears that the vessels are getting stuck at next to orbital collectors. This can be reproduced even with vanilla Orbital Collector.
The Gas Giant is located approx ~10AU from home planet. 

![stuck](https://user-images.githubusercontent.com/12244211/109429583-63398200-79ca-11eb-8b67-31391d209fa7.png)
![stuck_1](https://user-images.githubusercontent.com/12244211/109429584-63d21880-79ca-11eb-8b73-ec2dc764f915.png)

**Actual Behavior**:
Logistic Vessel getting stuck at next to orbital collector.

**Expected Behavior**:
Logistic vessels should not get stuck at next to orbital collector, and go straight into the collector.

**System**:
Touhma_GalacticScale 1.1.2

**Comment by Chrysaour** [comment] 2021-02-28 18:43
[data.zip](https://github.com/Touhma/DSP_Plugins/files/6057600/data.zip)

Attached save data file with configs.

**Comment by Chrysaour** [comment] 2021-02-28 19:30
It appears that even using ILS for planets which are close to the home planet (less than 0.1AU), logistic vessel gets stuck.

**Comment by JayVearrier** [comment] 2021-03-02 23:18
I can confirm that this is happening on my save as well. 

Interestingly enough, my ILS on another moon worked just fine (was on Aurohunen II-II with ILS on Aurohunen I-I, as an example) but my ILS on a gas giant (Hydrogen/Deuterium) in the same system (Aurohunen V) exhibited the same buggy behavior that's listed in this ticket. 

For what it's worth, I have the planet resizing portion of the mod turned off and I am using the GigaStationsv2 mod by Taki7o7 (using the Giga ILS in my example).

**Comment by GlitchHound** [comment] 2021-03-03 00:31
@Chrysaour were you also using GigaStations? You mentioned "even with vanilla stations" which leaves me wondering.

The fact that @JayVearrier reported this even with planet sizing turned off leads me to think its unlikely that our code is causing this and it seems entirely plausible that GigaStations is making a mistake while manipulating code relating to the logistics vessels (which we don't touch).

**Comment by JayVearrier** [comment] 2021-03-03 00:39
It could also be related to the gas giant that I'm having problems with - like I said, it works fine on the other telluric moon. What's curious is that when you're in sail mode, some of my planets/moons have the floating text ID'ing what is there and how far away; however, the gas giant that is being problematic (as well as at least one other gas giant in that system) don't have that floating text. 

I remember thinking to myself that it was odd that there wasn't floating text as I was cruising over there to put up those orbital collectors. I had to use the starmap just to make sure I was going to the right place since I didn't have the text. 

It's possible it's the GigaStation mod but it could be a combination of problems? Maybe that floating text isn't appearing because there's something wrong with the gas giant's data? Could also be related to this logistics vessel problem.

**Comment by Chrysaour** [comment] 2021-03-03 01:06
@GlitchHound  Yes, I was using GigaStations v2. 

Although, I tried both Giga ILS and Vanilla ILS and they didn't work. 

@JayVearrier  mentioned that it works on telluric moon, but it did not work on my end.
Vessels were stuck on planets/moon too.

**Comment by JayVearrier** [comment] 2021-03-03 01:26
Yeah, my ILS works just fine, which would indicate that the logistics vessels are moving just fine. That is, unless they behave differently for ILS vs. orbital collector - which wouldn't make sense why my ILS works and his doesn't. 

Here's some examples of the beautiful scene that is "suspended vessels." Note that the double-layered ones were when the collectors were ready to supply both Hydrogen and Deuterium. 

Again, not sure exactly where this is coming from. I opened up my game to double-check and get those images and I can definitely say that the 3 gas giants on the outer part of my system don't have the floating text like the other planets do. Looked around from the surface of my base and I could see floating text for the first planets but not for the gas giants. Again, not sure if that has anything to with this problem, just wanted to document that as well. 
![PlanetSurface](https://user-images.githubusercontent.com/79946600/109738000-aba09d80-7b8c-11eb-9d9c-fedcf77fa988.jpg)
![PlanetFromSpace](https://user-images.githubusercontent.com/79946600/109738009-afccbb00-7b8c-11eb-9bcf-9480d05e1047.jpg)

**Comment by innominata** [comment] 2021-03-03 08:40
I'm having this issue with vessels in my new system. Starter system was fine.
I've had vessels from tiny planet deliver to huge planet once. When they returned to tiny planet they got stuck at it.
I sent vessels from huge planet to pick up from tiny planet. They got stuck there. 
Now all vessels trying to deliver to huge planet are stuck here too :)
Also using gigastations, though not for interstellal logistics. Removing the mod doesn't help ships land. Faster vessels don't help (I thought maybe the modded planets were going too fast ;))
![Untitled-1](https://user-images.githubusercontent.com/4099099/109776720-c6941000-7c67-11eb-8a2b-1d0b75c66f19.jpg)

**Comment by GlitchHound** [comment] 2021-03-04 04:45
@innominata @Chrysaour @JayVearrier 
We don't run into this issue when testing without GigaStations. We can't currently commit to cross-mod compatibility, and we don't actually change anything that stations rely on, so I still want to point my finger at GigaStations.

In particular, I found a suspicious line of code here: https://github.com/WaGi-Coding/Taki_DSP-Mods/blob/0dcafa5fa63b2ac5c097c712f85a3dd7df2fb0c2/GigaStations/GigaStationsPlugin.cs#L794

That code, and code around it, shows that GigaStations is modifying stations (whether they're Giga- or not) in a way which assumes a particular planetary radius, rather than actually _reading_ the planet's radius. If true, this would point to a fundamental incompatibility which GigaStations would have to resolve, and it could certainly explain this issue.

Again, I don't want to imply I've taken the time to verify a seed is broken using vanilla stations when GigaStations is installed, and the same seed is not broken using vanilla stations when GigaStations is not installed. If anyone wants to install DSPCheats to test that scenario on a brand new seed, it'd be helpful, especially if you want to make the case that we're the ones breaking vanilla stations.

**Comment by Chrysaour** [comment] 2021-03-04 04:51
@GlitchHound  Thanks for investigation.

I believed GigaStations separated everything from vanilla stations.

That might explain things. Let me try out what you are suggesting.

**Comment by innominata** [comment] 2021-03-04 04:52
> @innominata @Chrysaour @JayVearrier
> We don't run into this issue when testing without GigaStations. We can't currently commit to cross-mod compatibility, and we don't actually change anything that stations rely on, so I still want to point my finger at GigaStations.
> 
> In particular, I found a suspicious line of code here: https://github.com/WaGi-Coding/Taki_DSP-Mods/blob/0dcafa5fa63b2ac5c097c712f85a3dd7df2fb0c2/GigaStations/GigaStationsPlugin.cs#L794
> 
> That code, and code around it, shows that GigaStations is modifying stations (whether they're Giga- or not) in a way which assumes a particular planetary radius, rather than actually _reading_ the planet's radius. If true, this would point to a fundamental incompatibility which GigaStations would have to resolve, and it could certainly explain this issue.
> 
> Again, I don't want to imply I've taken the time to verify a seed is broken using vanilla stations when GigaStations is installed, and the same seed is not broken using vanilla stations when GigaStations is not installed. If anyone wants to install DSPCheats to test that scenario on a brand new seed, it'd be helpful, especially if you want to make the case that we're the ones breaking vanilla stations.

Great find, I was planning on testing a brand new game without gigastations tonight to see if I could reproduce because I didn't want to assume it was a bug with this mod while running other things, but that line of code definitely looks like it could break non standard radius planets.

I'd much rather ditch giga and keep playing with galactic scale :) I'll update once I've either reproduced or failed (I'm betting failed, but I'll spend a good few hours trying everything I can think of)

**Comment by innominata** [comment] 2021-03-04 05:33
@Chrysaour Reproduced on first planet I tried. Seed 70658578 200 Stars
Asezai - VIII requesting from I-I single ILS with artificial sun on each planet.

![Untitled-12](https://user-images.githubusercontent.com/4099099/109916135-f1d63800-7d17-11eb-8326-e747a82641b5.jpg)

**Comment by GlitchHound** [comment] 2021-03-04 05:35
@innominata Thanks! Now, fingers crossed, if it is on us then hopefully it's fixed in the next build where we've made some pretty sweeping changes for compatibility. I can take this data to repro easily and figure that out (but tonight I have to sleep, so expect me to return back tomorrow evening).

**Comment by innominata** [comment] 2021-03-04 05:40
@GlitchHound Sleep well ! :D I'm going to disable every other mod I've got just to make sure its not something crazy.

**Comment by innominata** [comment] 2021-03-04 06:02
Reproduced using only Galactic Scale (Trainer for cheats, didn't feel like playing for 20 hours :))
#93408685-64-A10 Everything left default
Ships from Mara - I get stuck at IX

**Comment by innominata** [comment] 2021-03-05 01:38
Just re read the patch notes after the new one dropped today, and I may not have deleted my previous versions config when updating. probably nothing, but I'll make sure I do that and check again.

**Comment by innominata** [comment] 2021-03-05 04:07
Just reproduced after updating to 1.1.2.1 beta, and deleting config.
Large planet, the vessels clip through the planet and get stuck inside, can only find them if you go to map view and clip the camera through the planet. then you can see them all sitting there, like you would normally be able to see them sitting above the planet waiting.

Seed 41676523-64-A10, no other mods installed.
Planet they cannot land at was Amsen - VII

This planet also lacks a name tag in sail mode, I was thinking this might be a clue but I remember them also failing on inner planets that were named in previous tests, so it's not that.

**Comment by JJoschy** [comment] 2021-03-05 09:46
Have the same Problem (orbital Collector dont collect by planets that have no name tag in sail mod)
I Think it have to do with
numbers of planets / bodys in one system  or
to high distance distance from the sun

**Comment by JJoschy** [comment] 2021-03-05 10:34
I make some Testing with system with many planets
Planets - Moons - First No Name Planet - his Distance from star - Star Typ
10 - 12 - V - 6,5 AU - O
10 - 10- V - 10 AU - O
8 - 9 - V - 7 AU - O
6 - 9 - VI - 10 AU - A
9 - 8 - V - 11 AU - O
6 - 5 - VI - 14 AU - B

**Comment by GlitchHound** [comment] 2021-03-06 00:39
Apparently the latest patches have changed stargen. The seeds listed here don't have the planet names listed here right now.

Most importantly, either @Chrysaour or @innominata - did you reproduce in the starter systems in these seeds, or did you have to go to other systems? I think one of you mentioned both target and source being in the same system, is that true or does this only happen at interstellar scales?

**Comment by GlitchHound** [comment] 2021-03-06 00:46
Ignore me, might've been a config issue. Found Asezai in the first reported seed...

**Comment by innominata** [comment] 2021-03-06 01:28
@GlitchHound I didn't attempt in starter systems, as I've been rushing warp to start again in an organic O system :) I'll try and see if I can find a pattern in the issues

**Comment by innominata** [comment] 2021-03-06 02:45
Couldn't reproduce in starter system or nearby system, travelled to O type system and reproduced on a large planet.
Seems to be something related to scale, as the orbital distances involved are large. I'll try and reproduce it on an inner planet.
Save attached, with mecha staring at stuck vessels ;)

[test.zip](https://github.com/Touhma/DSP_Plugins/files/6094561/test.zip)

**Comment by innominata** [comment] 2021-03-06 03:05
I'm starting to wonder if its a precision error in the game engine. I haven't looked at any of the code or anything, but I remember it being a big thing when star citizen moved to 64 bit so they didn't have kilometer discrepancies  on the location of a coffee cup at the other side of the solar system. I could imagine if the ships are using polar coordinates at some point and there aren't enough decimal places, they could end up 50m away from where they expect to be, and glitch out when they try and convert their universe coordinate to local planet coordinate. I'll try changing the config so planet sizes dont change, but orbit is still huge.

I have however, just ruled out warpers, ships still get stuck even if they use standard drives.

**Comment by Chrysaour** [comment] 2021-03-06 04:51
@innominata  Probably not. 

I CANNOT reproduce this issue on 420 stars system with EnableResizingFeature False and EnableCustomStarAlgorithm False.

I think if we set EnableCustomStarAlgorithm  to True, then this problem occurs.

**Comment by GlitchHound** [comment] 2021-03-06 05:22
@Chrysaour @innominata Your first hunches were actually closer to right. The game hardcodes an upper bound of 10 planet bodies in a few places. This includes sail mode's planet name overlays AND some of the navigation code for transports.

Fix will be included in next update :)

**Comment by innominata** [comment] 2021-03-06 05:36
@Chrysaour  I've reproduced with Planet Resizing turned off, but only on planets with a large orbital radius. I.e. O Type star outer planets. I'm currently trying to reproduce on inner planets. I've also noticed some planets are orbiting outside their own system, which may be the reason they have no name tag, and may be related to this.

And you've figured it out :)

**Comment by GlitchHound** [comment] 2021-03-06 20:12
Officially fixed in the branch, next update will resolve. Thanks again for all the help and patience!

**Closed** 2021-03-06 23:14 UTC
Labels: Fixed, bug
