### ISSUE TITLE
Can't Generate Planets for Home Systems

### ISSUE THREAD

**Issue by kawika98** [Touhma/DSP_Plugins#9] opened 2021-02-18 00:05 UTC
17068013 : Seed used

When changing values for the G-star does not change the home system number of planets, gas giants, moons, or rocky planets the size of gas giants

**Comment by ZorbZorbZorb** [comment] 2021-02-18 15:42
Locked planet count is highly likely to be caused by this code in StarGen.CreateStarPlanets 

![image](https://user-images.githubusercontent.com/78667749/108380772-2bb22500-71d5-11eb-9fc8-925cf3569d6d.png)

![image](https://user-images.githubusercontent.com/78667749/108381555-ea6e4500-71d5-11eb-8630-1b82a055e39c.png)

**Comment by Touhma** [comment] 2021-02-18 17:11
His problem is because the custom generator is disabled , mainly because of an issue with the spawn planet :)

**Comment by Touhma** [comment] 2021-02-19 01:39
Shoud be fixed with 1.0.6 :)

**Closed by Touhma** 2021-02-19 01:39 UTC
Labels: bug
