### ISSUE TITLE
Planets and Stars Visible Through Home Planet Surface

### ISSUE THREAD

**Issue by slinkletter** [Touhma/DSP_Plugins#61] opened 2021-03-12 23:23 UTC
![See-Through Planet](https://user-images.githubusercontent.com/47759979/111008820-8a436c80-8357-11eb-863a-4dc6e6e7e062.jpg)

Can't remember this happening in vanilla.  You can select the pushpin and set it, too.  Very handy.

**Comment by GlitchHound** [comment] 2021-03-13 05:42
Confirmed it's NOT in vanilla. Will investigate.

**Comment by innominata** [comment] 2021-03-13 09:47
I haven't been able to reproduce in latest grid_test branch

**Comment by Shad0wlife** [comment] 2021-03-13 11:19
If it still happens, it might be that only the original 200 Planet size occludes and on larger planets if you have the right location and angle you might see through the planet. Because the pole markers are also locked to size 200 atm I think.

**Comment by GlitchHound** [comment] 2021-03-14 02:21
Turns out for some reason there was a 10-body limit on the occlusion checking code as well. Same fix works once we pointed it in the right place. Will be in next patch.

**Closed** 2021-03-22 22:02 UTC
Labels: Fixed, bug
