### ISSUE TITLE
Random planets with bad orbital period

### ISSUE THREAD

**Issue by gtbateman** [Touhma/DSP_Plugins#130] opened 2021-08-02 05:18 UTC
There is a bug in the Sol generator that causes about 1-5 percent of random planets to receive a default value for orbital period of 1000.  This results in excessively fast orbital speeds in most cases, and may be related to the bug reported by others where their mecha or ships bounce off some planets when attempting to land.

I encountered this with a Sol generator system with 500 stars (~2500 planets), and found 60 planets with this value.

I don't know if this bug is exclusive to the Sol generator - I have not tested for this specific issue with the other generators yet.

**Comment by innominata** [comment] 2021-08-02 20:16
Thanks for the report, fixed in the next update! (Not the root cause, but I've changed the failsafe to 100'000s instead of 1000).
Sol Generator will be getting it's prog-gen code replaced soon once dev gen is solid.

**Comment by gtbateman** [comment] 2021-08-02 23:50
Thanks - for now I just recalculated the periods for them in my custom json file.  Do you know the root cause?  Seems like a really strange bug - but apparently its defaulting to that value when it fails an error check or something?
Agree 100K would much better fallback value and put you in the ballpark most of the time.

Thanks,
TB
    On Monday, August 2, 2021, 1:16:18 PM PDT, innominata ***@***.***> wrote:  
 
 


Thanks for the report, fixed in the next update! (Not the root cause, but I've changed the failsafe to 100'000s instead of 1000).
Sol Generator will be getting it's prog-gen code replaced soon once dev gen is solid.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by innominata** [comment] 2021-08-03 00:08
Haven't bothered looking for the cause yet, busy reworking the settings UI so we can add a bunch more options. The next version will change the orbital period of any existing planets that are at 1000 to 100k, so should fix existing saves.

**Comment by innominata** [comment] 2021-08-11 20:10
Should be fixed

**Closed by innominata** 2021-08-11 20:10 UTC
